export type BeliPlace = {
  rank: number;
  name: string;
  score: number;
  price: "$" | "$$" | "$$$";
  tags: string;
  location: string;
};

export const BELI_CATEGORY = "Coffee & Tea";

export type BeliTab = "been" | "want";

export type BeliWantToTry = {
  name: string;
  price: "$" | "$$" | "$$$";
  tags: string;
  location: string;
};

/** Static snapshot of Want to Try. Update by hand when the list changes. */
export const BELI_WANT_TO_TRY: readonly BeliWantToTry[] = [
  {
    name: "Loquat Coffee Cypress Park",
    price: "$$",
    tags: "Coffee Shop",
    location: "Northeast Los Angeles, Los Angeles, CA",
  },
  {
    name: "ELOREA",
    price: "$$",
    tags: "Drinks, Matcha, Tea",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    name: "MEMORYLOOK COFFEE & FLAGSHIP STORE",
    price: "$$",
    tags: "Coffee Shop, Matcha",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    name: "RNY Coffee Studio",
    price: "$",
    tags: "Coffee, Coffee Shop, Korean",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    name: "SYNT Coffee",
    price: "$$",
    tags: "Coffee, Tea, Dessert",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    name: "The Moon Café",
    price: "$$",
    tags: "",
    location: "North Hollywood, Los Angeles, CA",
  },
  {
    name: "koffeeski",
    price: "$",
    tags: "Cafe, Matcha, Coffee",
    location: "Central LA, Los Angeles, CA",
  },
  {
    name: "RE: COFFEE",
    price: "$$",
    tags: "Coffee Shop, Matcha",
    location: "Northridge, Los Angeles, CA",
  },
  {
    name: "Bonsai Coffee & Bar",
    price: "$$",
    tags: "Cafe, Coffee, Matcha",
    location: "Sawtelle, Los Angeles, CA",
  },
  {
    name: "GoodPeople",
    price: "$$",
    tags: "Coffee, Breakfast",
    location: "West Los Angeles, Los Angeles, CA",
  },
];

/** Static snapshot of the Been list. Update by hand when the ranking changes. */
export const BELI_PLACES: readonly BeliPlace[] = [
  {
    rank: 1,
    name: "rök",
    score: 10.0,
    price: "$$",
    tags: "Matcha, Coffee, Korean",
    location: "Central LA, Los Angeles, CA",
  },
  {
    rank: 2,
    name: "DAMO",
    score: 9.9,
    price: "$",
    tags: "Matcha, Coffee Shop, Coffee",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 3,
    name: "Community Goods",
    score: 9.8,
    price: "$$",
    tags: "Matcha, Coffee Shop, Coffee",
    location: "Melrose, Los Angeles, CA",
  },
  {
    rank: 4,
    name: "STAGGER COFFEE",
    score: 9.7,
    price: "$$",
    tags: "Coffee Shop, Matcha",
    location: "",
  },
  {
    rank: 5,
    name: "Archives Of Us",
    score: 9.6,
    price: "$$",
    tags: "Coffee, Matcha",
    location: "Downtown Los Angeles, CA",
  },
  {
    rank: 6,
    name: "danbi coffee",
    score: 9.5,
    price: "$$",
    tags: "Matcha, Coffee, Korean",
    location: "Pasadena, CA",
  },
  {
    rank: 7,
    name: "Yeems Coffee",
    score: 9.4,
    price: "$$",
    tags: "Matcha, Coffee",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 8,
    name: "La Vi - Vietnamese Coffee",
    score: 9.3,
    price: "$",
    tags: "Coffee, Vietnamese, Food Truck",
    location: "Downtown Austin, Austin, TX",
  },
  {
    rank: 9,
    name: "Porto's Bakery and Cafe",
    score: 9.2,
    price: "$",
    tags: "Bakery, Cuban, Sandwiches",
    location: "Downtown, Glendale, CA",
  },
  {
    rank: 10,
    name: "The tea.",
    score: 9.2,
    price: "$$",
    tags: "Bubble Tea",
    location: "Monterey Park, CA",
  },
  {
    rank: 11,
    name: "Matsu Matcha Koreatown",
    score: 9.1,
    price: "$$",
    tags: "Matcha, Gelato",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 12,
    name: "Taty's Specialty Coffee & Tea",
    score: 9.0,
    price: "$",
    tags: "Coffee, Tea, Matcha",
    location: "Garden Grove, CA",
  },
  {
    rank: 13,
    name: "Miopane",
    score: 8.9,
    price: "$$",
    tags: "Taiwanese, Bakery, Bagels",
    location: "Old Pasadena, Pasadena, CA",
  },
  {
    rank: 14,
    name: "Molly Tea (Arcadia)",
    score: 8.8,
    price: "$$",
    tags: "Bubble Tea, Tea, Matcha",
    location: "Arcadia, CA",
  },
  {
    rank: 15,
    name: "Onescape Coffee",
    score: 8.7,
    price: "$$",
    tags: "Cafe, Matcha, Coffee Shop",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 16,
    name: "Sobuneh",
    score: 8.6,
    price: "$$",
    tags: "Breakfast, Persian",
    location: "Central LA, West Hollywood, CA",
  },
  {
    rank: 17,
    name: "Yala Coffee",
    score: 8.5,
    price: "$$",
    tags: "Coffee, Matcha",
    location: "Studio City, Los Angeles, CA",
  },
  {
    rank: 18,
    name: "La La Land",
    score: 8.4,
    price: "$$",
    tags: "Coffee, Tea, Cafe",
    location: "Downtown Los Angeles, CA",
  },
  {
    rank: 19,
    name: "CHAGEE Americana",
    score: 8.3,
    price: "$",
    tags: "Chinese, Bubble Tea",
    location: "Downtown, Glendale, CA",
  },
  {
    rank: 20,
    name: "Mandarin 2",
    score: 8.2,
    price: "$",
    tags: "Coffee Shop, Tea, Chinese",
    location: "Pasadena, CA",
  },
  {
    rank: 21,
    name: "Leaf & Cloud Matcha Cafe",
    score: 8.1,
    price: "$$",
    tags: "Matcha, Cafe",
    location: "Downtown, Glendale, CA",
  },
  {
    rank: 22,
    name: "Tea Master Matcha Cafe and Green Tea Shop",
    score: 8.0,
    price: "$",
    tags: "Japanese, Matcha, Ice Cream",
    location: "Downtown Los Angeles, CA",
  },
  {
    rank: 23,
    name: "Tea Drip",
    score: 7.9,
    price: "$$",
    tags: "Cafe, Vietnamese, Matcha",
    location: "Gwinnett Place, Duluth, GA",
  },
  {
    rank: 24,
    name: "Alfred Coffee",
    score: 7.8,
    price: "$$",
    tags: "Coffee Shop, Coffee, Matcha",
    location: "Westwood, Los Angeles, CA",
  },
  {
    rank: 25,
    name: "Olive and James Cafe Tea - Melrose",
    score: 7.7,
    price: "$$",
    tags: "Coffee Shop, Tea, Matcha",
    location: "Fairfax, Los Angeles, CA",
  },
  {
    rank: 26,
    name: "Loop Espresso Club",
    score: 7.6,
    price: "$$$",
    tags: "Coffee",
    location: "Northeast Los Angeles, CA",
  },
  {
    rank: 27,
    name: "Maru Coffee",
    score: 7.5,
    price: "$",
    tags: "Coffee Shop, Matcha, Coffee",
    location: "Los Feliz, Los Angeles, CA",
  },
  {
    rank: 28,
    name: "Motiq",
    score: 7.5,
    price: "$$",
    tags: "Matcha, Cafe, Coffee",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 29,
    name: "Artisanal Goods by CAR (CAR Artisan Chocolate)",
    score: 7.4,
    price: "$$$",
    tags: "Bakery",
    location: "Catalina Villas, Pasadena, CA",
  },
  {
    rank: 30,
    name: "Salted Butter Company",
    score: 7.3,
    price: "$$",
    tags: "Bakery",
    location: "South Arroyo, Pasadena, CA",
  },
  {
    rank: 31,
    name: "CHICHA San Chen - Sawtelle",
    score: 7.2,
    price: "$$",
    tags: "Bubble Tea, Tea, Taiwanese",
    location: "Sawtelle, Los Angeles, CA",
  },
  {
    rank: 32,
    name: "Café Tondo",
    score: 7.1,
    price: "$$$",
    tags: "Mexican, Bar, Cafe",
    location: "Central LA, Los Angeles, CA",
  },
  {
    rank: 33,
    name: "Everbloom Coffee - Downtown",
    score: 7.0,
    price: "$",
    tags: "Cafe, Coffee, Coffee Shop",
    location: "Indio, CA",
  },
  {
    rank: 34,
    name: "In-sit Coffee - Buena Park",
    score: 6.9,
    price: "$$",
    tags: "Coffee, Coffee Shop",
    location: "Buena Park, CA",
  },
  {
    rank: 35,
    name: "How's It Going To End?",
    score: 6.8,
    price: "$$",
    tags: "Coffee Shop",
    location: "Montrose, Glendale, CA",
  },
  {
    rank: 36,
    name: "Immersion Coffee",
    score: 6.7,
    price: "$",
    tags: "Cafe, Coffee Shop",
    location: "La Jolla, San Diego, CA",
  },
  {
    rank: 37,
    name: "mandarin coffee stand",
    score: 6.5,
    price: "$$",
    tags: "Coffee, Matcha",
    location: "Pasadena, CA",
  },
  {
    rank: 38,
    name: "Three Fields Coffee",
    score: 6.3,
    price: "$$",
    tags: "Coffee Shop",
    location: "Alhambra, CA",
  },
  {
    rank: 39,
    name: "Summerfield Tea Bar",
    score: 6.0,
    price: "$$",
    tags: "Bubble Tea, Tea",
    location: "Rosemead, CA",
  },
  {
    rank: 40,
    name: "Cafe Dulce (USC Village)",
    score: 5.8,
    price: "$$",
    tags: "Cafe, Coffee, Matcha",
    location: "South Los Angeles, CA",
  },
  {
    rank: 41,
    name: "Spot Coffee & More",
    score: 5.6,
    price: "$$",
    tags: "Dessert, Cafe",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 42,
    name: "Reborn Coffee - La Crescenta",
    score: 5.4,
    price: "$$",
    tags: "Coffee Shop",
    location: "Crescenta Highlands, Glendale, CA",
  },
  {
    rank: 43,
    name: "LABORA",
    score: 5.2,
    price: "$$",
    tags: "Matcha, Coffee, Cafe",
    location: "Kearny Mesa, San Diego, CA",
  },
  {
    rank: 44,
    name: "DASH COFFEE BAR",
    score: 4.9,
    price: "$$",
    tags: "Coffee Shop",
    location: "Catalina Villas, Pasadena, CA",
  },
  {
    rank: 45,
    name: "Bag of Cakes",
    score: 4.7,
    price: "$$",
    tags: "Bakery, Cake, Coffee Shop",
    location: "Northwood, Irvine, CA",
  },
  {
    rank: 46,
    name: "Easy Does It",
    score: 4.5,
    price: "$$",
    tags: "Matcha, Coffee, Cafe",
    location: "Kearny Mesa, San Diego, CA",
  },
  {
    rank: 47,
    name: "About Time",
    score: 4.3,
    price: "$$",
    tags: "Coffee, Tea, Matcha",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 48,
    name: "Kissa by Motto",
    score: 4.1,
    price: "$$",
    tags: "Tea, Cafe, Bakery",
    location: "South Arroyo, Pasadena, CA",
  },
  {
    rank: 49,
    name: "Dumbstruck Coffee - LA",
    score: 3.8,
    price: "$",
    tags: "Cafe, Matcha, Coffee",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 50,
    name: "CAFE UPPER",
    score: 3.6,
    price: "$",
    tags: "Coffee, Matcha",
    location: "Koreatown, Los Angeles, CA",
  },
  {
    rank: 51,
    name: "Blank Street Coffee",
    score: 3.4,
    price: "$",
    tags: "Coffee Shop, Coffee, Matcha",
    location: "SoHo, Manhattan",
  },
  {
    rank: 52,
    name: "LEORA",
    score: 2.6,
    price: "$$$",
    tags: "Cafe, American, Mediterranean, Israeli",
    location: "Beverly Hills, CA",
  },
  {
    rank: 53,
    name: "Pinpoint Cafe",
    score: 1.8,
    price: "$$",
    tags: "Açaí Bowls, Breakfast, Cafe",
    location: "La Jolla, San Diego, CA",
  },
  {
    rank: 54,
    name: "Milk Brew",
    score: 0.9,
    price: "$$",
    tags: "Coffee, Coffee Shop",
    location: "Pasadena, CA",
  },
] as const;

export function beliScoreTone(score: number): "high" | "mid" | "low" {
  if (score >= 6.8) return "high";
  if (score >= 4) return "mid";
  return "low";
}

export function formatBeliScore(score: number) {
  return score.toFixed(1);
}
